services:
  #=================== TCP 80
  tcp-80:
    build:
      context: ./tcp-80
    image: tcp-80
    container_name: tcp-80
    ports:
      - "80:80/tcp"
    restart: always
  #=================== UDP 1024
  udp-1024:
    build:
      context: ./udp-1024
    image: udp-1024
    container_name: udp-1024
    ports:
      - "1024:1024/udp"
    restart: always
